live_config_reload = true

[cursor]
style = "Beam"

[font]
size = 12.0

[font.normal]
family = "NotoMono Nerd Font" 
[window]
startup_mode = "Windowed"
dynamic_padding = true
opacity = 0.85

[window.padding]
x = 6
y = 0

[window.dimensions]
columns = 150
lines = 40


# Colors (Ayu Dark)

# Default colors
[colors.primary]
background = '#0A0E14'
foreground = '#B3B1AD'

# Normal colors
[colors.normal]
black   = '#01060E'
red     = '#EA6C73'
green   = '#91B362'
yellow  = '#F9AF4F'
blue    = '#53BDFA'
magenta = '#FAE994'
cyan    = '#90E1C6'
white   = '#C7C7C7'

# Bright colors
[colors.bright]
black   = '#686868'
red     = '#F07178'
green   = '#C2D94C'
yellow  = '#FFB454'
blue    = '#59C2FF'
magenta = '#FFEE99'
cyan    = '#95E6CB'
white   = '#FFFFFF'

[colors.cursor]
text = "CellBackground"
cursor = "CellForeground"



